### ISSUE TITLE
tracemap显示问题

### ISSUE THREAD

**Issue by StrollStars** [tsosunchia/traceMap#17]
## 你正在使用哪个版本的 nexttrace？

nexttrace_windows_amd64.exe
Windows 7 64bit
Chrome 109.0.5414.75
Firefox 115.4.0

## 你看到的异常现象是什么？

1. Chrome下tracemap的路由表过长，会导致靠近头（路由表表头）和尾（Tips）部分显示在网页外，而Firefox下正相反，除了路由表表头和Tips，什么都没显示。
2. 进入3D视角后，好像无法通过右键菜单退出，因为没有右键菜单。

## 你期待看到的正常表现是怎样的？
1. 和[演示图](https://user-images.githubusercontent.com/59512455/218504874-06b9fa4b-48e0-420a-a195-08a1200d65a7.png)一样的效果，可以看到路由表的表头和底下的Tips（Chrome下）。
2. 进入3D视角后，能通过右键菜单退出。

**Comment by tsosunchia** [comment]
请举一个具体的例子

**Comment by isyekong** [comment]
您好，请把该tracemap url发一下，方便我们定位问题

**Comment by StrollStars** [comment]
@isyekong 我又测试了其他平台和浏览器，还是存在问题，链接已发送邮箱。
